/* measure.html — the phone-side data-entry sheet for the measurement program.
   ------------------------------------------------------------------
   Two things can go wrong here and neither is visible by looking at the page:

   1. THE SHEET DRIFTS FROM THE FIXTURE SCHEMA. measure.html embeds the
      tests/data templates so its export lands as a file `status.js` and the
      solver already understand. A template edited on disk and not here would
      still export cleanly — into the wrong shape, discovered weeks later with
      a session's readings already in it. So every embedded template is
      compared against the file it claims to be, on both the reading slots it
      offers and the values it says to SET. A row that says arF 40 in the file
      and 45 on the phone is a measurement of nothing.

   2. A ROW GOES MISSING FROM THE FORM. The form is generated by walking the
      template rather than from a hand-written field list, precisely so this
      cannot happen — but the walk has rules (skip _keys, skip context keys,
      recurse into arrays and objects) and a rule that is slightly wrong drops
      a case silently. Every null-or-empty leaf in every template must come
      back as a reachable field.

   Run under the same plain-Node DOM shim idea as the rest of the suite; this
   file carries its own because measure.html needs a little more DOM than
   index.html does (details/summary, dialog, dataset queries). */
const fs = require('fs');
const path = require('path');
const { ok } = require('./shim');

const ROOT = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(ROOT, 'measure.html'), 'utf8');
const src = html.split('<script>')[1].split('</' + 'script>')[0];

/* ---- the least DOM that lets the page's own code run ------------------- */
function fakeEl() {
  const e = {
    innerHTML: '', textContent: '', value: '', className: '', open: false,
    dataset: {}, style: {}, onclick: null,
    classList: { add() {}, remove() {}, toggle() {} },
    querySelectorAll: () => [], querySelector: () => null,
    closest: () => null, showModal() {}, close() {}, focus() {},
    scrollIntoView() {}, click() {}, appendChild() {}
  };
  return e;
}
const els = {};
const document = {
  getElementById: id => els[id] || (els[id] = fakeEl()),
  querySelector: () => null,
  querySelectorAll: () => [],
  addEventListener() {},
  createElement: () => fakeEl()
};
const store = {};
const localStorage = {
  getItem: k => (k in store ? store[k] : null),
  setItem: (k, v) => { store[k] = v; },
  removeItem: k => { delete store[k]; }
};
const api = new Function(
  'document', 'window', 'localStorage', 'navigator', 'URL', 'Blob', 'confirm', 'alert',
  src + '\n;return {SESSIONS, newDoc, render, build, filename, setVal, doc, fillHeld,' +
        ' getFields: () => FIELDS};'
)(document,
  { scrollTo() {}, innerWidth: 390 },
  localStorage,
  { /* no share, no clipboard — the export dialog is not exercised here */ },
  { createObjectURL: () => 'blob:x', revokeObjectURL() {} },
  class { constructor(p) { this.parts = p; } },
  () => true, () => {});

const { SESSIONS, newDoc, render, build, filename, setVal, fillHeld, getFields } = api;

/* ---- walking a template the way the form is specified to ---------------- */
const isLeaf = v => v === null || v === '' || typeof v !== 'object';
const empty = v => v === null || v === '';
/* keys that describe a row rather than being a reading in it — must match the
   CTX set in measure.html, and are asserted against it below by construction:
   any drift shows up as a slot the form offers that the template does not, or
   the reverse. */
const CTX = new Set(['n', 'purpose', 'changed', 'part', 'tune', 'change', 'name', 'id',
  'options', 'usedBy', 'impliedK', 'vmetaLo', 'vmetaHi']);
const TOP_SKIP = new Set(['screen', 'case', 'varied', 'readout', 'notes']);

/* Every reading slot: an empty leaf reachable without passing through a _key,
   excluding the free-text notes box and the row-context keys. */
function slots(tpl) {
  const out = [];
  (function walk(node, base, depth) {
    for (const k of Object.keys(node)) {
      if (k.startsWith('_')) continue;
      if (depth === 0 && TOP_SKIP.has(k)) continue;
      if (depth > 0 && CTX.has(k)) continue;
      if (depth > 0 && k === 'note') continue;   /* baseline.note is prose */
      const v = node[k], p = base ? base + '.' + k : k;
      if (isLeaf(v)) { if (empty(v)) out.push(p); }
      else if (Array.isArray(v)) v.forEach((el, i) => walk(el, p + '.' + i, depth + 1));
      else walk(v, p, depth + 1);
    }
  })(tpl, '', 0);
  return out;
}

/* Every value the template says to SET before reading — the held conditions. */
function held(tpl) {
  const out = {};
  (function walk(node, base, depth) {
    for (const k of Object.keys(node)) {
      if (k.startsWith('_')) continue;
      const v = node[k], p = base ? base + '.' + k : k;
      if (isLeaf(v)) { if (!empty(v)) out[p] = v; }
      else if (Array.isArray(v)) v.forEach((el, i) => walk(el, p + '.' + i, depth + 1));
      else walk(v, p, depth + 1);
    }
  })(tpl, '', 0);
  return out;
}

const load = f => JSON.parse(fs.readFileSync(path.join(ROOT, 'tests', 'data', f), 'utf8'));
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);

console.log('\n--- measure.html: fidelity to the fixture templates ---');

/* Which embedded template must equal which file on disk. The aero sheet and
   the gearing sheet have no template of their own — the aero row plan lives as
   prose in the balance template's _AERO_ROWS, and the only gearing file on
   disk is the GR86 measurement itself — so those two are checked for internal
   reachability only, below. */
const MIRRORS = [
  ['ranges', 'ranges-TEMPLATE.json'],
  ['parts',  'parts-TEMPLATE.json'],
  ['panel',  'panel-TEMPLATE.json'],
  ['mb',     'balance-TEMPLATE.json']
];

for (const [sid, file] of MIRRORS) {
  const sess = SESSIONS.find(s => s.id === sid);
  const disk = load(file);
  const a = slots(sess.tpl).sort(), b = slots(disk).sort();
  ok(sid + ': offers exactly the reading slots ' + file + ' has', same(a, b),
    same(a, b) ? '' : 'form-only ' + JSON.stringify(a.filter(x => !b.includes(x))) +
      ' file-only ' + JSON.stringify(b.filter(x => !a.includes(x))));

  const ha = held(sess.tpl), hb = held(disk);
  const bad = Object.keys(hb).filter(k => !(k in ha) || ha[k] !== hb[k]);
  ok(sid + ': every held/set value matches ' + file, bad.length === 0,
    bad.length ? bad.map(k => k + ' form=' + ha[k] + ' file=' + hb[k]).join(', ') : '');
}

console.log('\n--- every reading slot is reachable as a field ---');

for (const sess of SESSIONS) {
  newDoc(sess.id);
  render();
  const fields = getFields().slice();
  const want = slots(sess.tpl);
  const missing = want.filter(p => !fields.includes(p));
  const extra = fields.filter(p => !want.includes(p));
  ok(sess.id + ': all ' + want.length + ' slots rendered', missing.length === 0,
    missing.length ? 'missing ' + JSON.stringify(missing.slice(0, 6)) : '');
  ok(sess.id + ': no field that is not a slot in the fixture', extra.length === 0,
    extra.length ? 'extra ' + JSON.stringify(extra.slice(0, 6)) : '');
  ok(sess.id + ': no duplicate field paths',
    new Set(fields).size === fields.length);
}

console.log('\n--- the gating matrix takes yes/no, not a keyboard ---');
{
  const sess = SESSIONS.find(s => s.id === 'parts');
  newDoc('parts'); render();
  const gate = getFields().filter(p =>
    /^(suspension|differential|antirollBars|transmission|aero)\./.test(p));
  ok('parts: gating questions exist', gate.length > 30, gate.length + ' found');
  ok('parts: every gating question is a tri-state, not a number field',
    gate.every(p => sess.bools.test(p)));
  /* P2/P3 are readings, not gates, and must NOT be caught by that regex */
  const reads = getFields().filter(p => /^P[23]/.test(p));
  ok('parts: P2/P3 stat-block readings stay numeric',
    reads.length > 0 && reads.every(p => !sess.bools.test(p)), reads.length + ' rows');
}

console.log('\n--- export: what is typed is what lands, where the solver looks ---');
{
  newDoc('mb'); render();
  setVal('car', '2020 Toyota Supra');
  setVal('date', '2026-08-12');
  setVal('rows.0.mb', '0.5');
  setVal('rows.1.mb', '0.487');
  setVal('build.wt', '3400');
  const out = build();
  ok('mb: readings land on the row the solver reads',
    out.rows[0].mb === 0.5 && out.rows[1].mb === 0.487,
    JSON.stringify([out.rows[0].mb, out.rows[1].mb]));
  ok('mb: numbers export as numbers, not strings',
    typeof out.rows[0].mb === 'number' && typeof out.build.wt === 'number');
  ok('mb: text stays text', out.car === '2020 Toyota Supra' && typeof out.car === 'string');
  ok('mb: untouched slots stay null, so status.js still counts them as to-do',
    out.rows[2].mb === null && out.rows[14].mb === null);
  ok('mb: the held values survive the round trip untouched',
    out.rows[2].arF === 40 && out.rows[2].arR === 80 && out.readout === 'mb');
  ok('mb: the template README rides along', Array.isArray(out._README));
}
{
  newDoc('parts'); render();
  setVal('suspension.street.damping', '0');
  setVal('suspension.race.damping', '1');
  const out = build();
  ok('parts: yes/no export as booleans',
    out.suspension.race.damping === true && out.suspension.street.damping === false,
    JSON.stringify([out.suspension.race.damping, out.suspension.street.damping]));
  ok('parts: untested tiers stay null, not false',
    out.suspension.rally.damping === null);
}

console.log('\n--- filling held values never overwrites a deliberate one ---');
{
  /* Rows 4-7 of a balance sweep exist BECAUSE a held value was moved. If the
     one-tap fill overwrote them they would become duplicates of row 1 while
     still carrying their own readout — fifteen rows, four of them quietly
     lying about what they were taken under. */
  newDoc('mb'); render();
  setVal('baseline.spF', '520'); setVal('baseline.spR', '480');
  setVal('baseline.rhF', '4.5'); setVal('baseline.rhR', '4.7');
  setVal('rows.3.spF', '364');            /* row 4 is the -30% spring row */
  const n = fillHeld('rows');
  const out = build();
  ok('fill: row 4 keeps the value that makes it row 4', out.rows[3].spF === 364,
    String(out.rows[3].spF));
  ok('fill: the other rows take the baseline',
    out.rows[0].spF === 520 && out.rows[0].rhR === 4.7 && out.rows[14].spR === 480);
  ok('fill: it filled 15 rows x 4 held, less the one already set', n === 59, String(n));
  ok('fill: it did not touch the readout', out.rows[0].mb === null);

  const again = fillHeld('rows');
  ok('fill: running it twice changes nothing', again === 0, String(again));
}
{
  newDoc('mb'); render();
  const n = fillHeld('rows');
  ok('fill: with no baseline set it fills nothing rather than blanks', n === 0, String(n));
}

console.log('\n--- filenames keep the stem tests/status.js reads ---');
{
  /* status.js buckets a fixture by `f.split('-')[0]`, so the prefix is load
     bearing: a file named for the car first would be counted as its own topic
     and the case it answers would still read as unmeasured. */
  for (const sess of SESSIONS) {
    newDoc(sess.id); render();
    setVal('car', '2022 Toyota GR86');
    setVal('date', '2026-08-12');
    const f = filename();
    ok(sess.id + ' → ' + f, f.split('-')[0] === sess.stem && /\.json$/.test(f));
  }
  newDoc('ab'); render();
  setVal('car', 'Mazda RX-7'); setVal('date', '2026-08-12');
  ok('ab sheets are distinguishable from mb sheets at a glance',
    filename() === 'balance-ab-mazda-rx-7-2026-08-12.json', filename());
}

console.log('\n--- the standing rules are on the page, not just in the docs ---');
{
  /* The rules are the reason the sheet exists: a phone form that collects
     numbers without them is how you get fifteen rows where two things moved. */
  ok('one variable per observation', /One variable per observation/.test(html));
  ok('never measure geometry off a photo', /never measure geometry/i.test(html));
  ok('raw readings, never conclusions', /Record raw readings, never conclusions/.test(html));
  ok('a green suite means nothing was wired up',
    /green suite after new measurements/.test(html));
  ok('read the axis cold, before the candidates',
    /READ IT COLD/.test(html) && /do not read them first/i.test(html));
}
